Repository DAILAB-SUZY/PITCH, pull requests merged in 2024-10, with the labels that each got.

#122 feat: authentication deny redirection수정
  backend/build.gradle
  backend/compose.yaml
  backend/src/main/java/org/cosmic/backend/domain/auth/applications/JwtAuthenticationFilter.java
  backend/src/main/java/org/cosmic/backend/domain/auth/applications/TokenProvider.java
  backend/src/main/java/org/cosmic/backend/domain/auth/dtos/UserLoginDetail.java
  backend/src/main/java/org/cosmic/backend/domain/user/apis/UserApi.java
  backend/src/main/java/org/cosmic/backend/domain/user/applications/UserService.java
  backend/src/main/java/org/cosmic/backend/domain/user/domains/MyUserDetails.java
  backend/src/main/java/org/cosmic/backend/domain/user/domains/User.java
  backend/src/main/java/org/cosmic/backend/globals/configs/RedisConfig.java
  backend/src/main/java/org/cosmic/backend/globals/configs/SecurityConfig.java
  backend/src/main/java/org/cosmic/backend/globals/filters/JwtAuthenticationFilter.java
  backend/src/main/java/org/cosmic/backend/globals/filters/JwtAuthenticationToken.java
  backend/src/main/resources-local/application.properties
  backend/src/main/resources-prod/application.properties
  backend/src/test/java/org/cosmic/backend/domainsTest/auth/ServletFilterTest.java
Labels: bug

#130 feat: 앨범스코어 관련 swagger추가
  backend/src/main/java/org/cosmic/backend/domain/albumScore/apis/AlbumScoreApi.java
Labels: enhancement

#131 feat: 이름 검색 시 유저 이름 포함하는 검색 기능 조정
  backend/src/main/java/org/cosmic/backend/domain/albumScore/applications/AlbumScoreService.java
  backend/src/main/java/org/cosmic/backend/domain/search/apis/SearchUserApi.java
  backend/src/main/java/org/cosmic/backend/domain/user/repositorys/UsersRepository.java
Labels: enhancement

#134 feat: 기본 프로필 조정
  backend/src/main/java/org/cosmic/backend/domain/user/domains/User.java
Labels: enhancement

#140 Hotfix/backend/favorite artist fix
  backend/src/main/java/org/cosmic/backend/domain/favoriteArtist/applications/FavoriteArtistService.java
  backend/src/main/java/org/cosmic/backend/domain/favoriteArtist/dtos/FavoriteArtistDetail.java
  backend/src/main/java/org/cosmic/backend/domain/favoriteArtist/exceptions/IdNullException.java
  backend/src/main/java/org/cosmic/backend/domain/musicProfile/dtos/MusicProfileDetail.java
  backend/src/main/java/org/cosmic/backend/domain/musicProfile/dtos/ProfileDetail.java
  backend/src/main/java/org/cosmic/backend/domain/user/domains/User.java
  backend/src/main/java/org/cosmic/backend/globals/exceptions/BadRequestException.java
Labels: bug, enhancement

#144 Hotfix/backend/build error
  backend/src/main/java/org/cosmic/backend/domain/user/domains/User.java
  backend/src/main/java/org/cosmic/backend/globals/configs/WebConfig.java
  backend/src/main/java/org/cosmic/backend/globals/controllers/WebController.java
Labels: bug
